[pytest]
testpaths = automacao/tests
pythonpath = automacao
bdd_features_base_dir = bdd/
base_url = https://www.saucedemo.com
addopts =
    --browser chromium
    --screenshot only-on-failure
    --output automacao/test-results
    --html=automacao/reports/relatorio.html
    --self-contained-html
    -rxX
